apiVersion: v1
kind: Service
metadata:
  name: savinov-ikbo-16-20
spec:
  selector:
    app: savinov-ikbo-16-20
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort