apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - image: catalog:latest
        imagePullPolicy: Never
        name: frontend
        env:
        - name: CATALOG_DB_URL
          value: "catalog-db"
        - name: CATALOG_DB_PORT
          value: "5432"
        - name: CATALOG_DB
          value: "catalogDB"
        - name: CATALOG_DB_USERNAME
          value: "admin"
        - name: CATALOG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-db-passwd
              key: passwd
        - name: KAFKA_URL
          value: "kafka-broker"
        - name: KAFKA_PORT
          value: "9092"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalog
  sessionAffinity: None
  type: ClusterIP