version: '3'

services:
  
  notifications-app:
    build: 
      context: ./notifications
    ports:
      - 8080:8080
    environment:
      - NOTIFICATIONS_DB_URL=postgres
      - NOTIFICATIONS_DB_PORT=5432
      - NOTIFICATIONS_DB=appDB
      - NOTIFICATIONS_DB_USERNAME=admin
      - NOTIFICATIONS_DB_PASSWORD=12345678
      - REDIS_WRITE_HOST=redis-write
      - REDIS_WRITE_PORT=6379
      - REDIS_READ_HOST=redis-read
      - REDIS_READ_PORT=6380
      - REDIS_PASSWORD=12345678
      - KAFKA_URL=kafka-broker
      - KAFKA_PORT=9092
    depends_on:
      - postgres
      - redis-write
      - redis-read
  
  catalog-app:
    build: 
      context: ./catalog
    ports:
      - 8081:8080
    environment:
      - CATALOG_DB_URL=postgres
      - CATALOG_DB_PORT=5432
      - CATALOG_DB=appDB
      - CATALOG_DB_USERNAME=admin
      - CATALOG_DB_PASSWORD=12345678
      - KAFKA_URL=kafka-broker
      - KAFKA_PORT=9092
    depends_on:
      - postgres

  postgres:
    image: postgres:15  
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: appDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./temp/psqlDB:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - 8082:8080
    depends_on: 
      - postgres

  redis-write:
    image: redis:7.2.1-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=12345678

  redis-read:
    image: redis:7.2.1-alpine
    ports:
      - 6380:6379
    command: redis-server --slaveof "redis-write" 6379 --masterauth "${REDIS_PASSWORD}" --requirepass "${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=12345678

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - 8083:8081
    environment:
      - REDIS_HOSTS=local:redis-write:6379
      - REDIS_PASSWORD=12345678
    depends_on:
      - redis-write
      - redis-read
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka-broker:
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker:9092"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper