apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: graylog
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:5.2
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: "1234567812345678"
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918" # admin
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: "http://localhost:9000/"
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        ports:
        - name: web-port
          containerPort: 9000
        - name: input-port
          containerPort: 12201
        command: ["/usr/bin/tini", "--", "wait-for-it", "elasticsearch:9200", "--", "/docker-entrypoint.sh"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
  name: graylog
spec:
  selector:
    app: graylog
  ports:
  - name: web-port
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: input-port
    port: 12201
    targetPort: 12201
    protocol: UDP