apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mongo
    type: local
  name: mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: mongoData
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo
  name: mongo-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data/db
      volumes:
      - name: mongodb-volume
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo