spring:

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${NOTIFICATIONS_DB_URL}:${NOTIFICATIONS_DB_PORT}/${NOTIFICATIONS_DB}
    username: ${NOTIFICATIONS_DB_USERNAME}
    password: ${NOTIFICATIONS_DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_WRITE_HOST}
      port: ${REDIS_WRITE_PORT}
      password: ${REDIS_PASSWORD}
      # cluster:
      #   nodes:
      #     - ${REDIS_WRITE_HOST}:${REDIS_WRITE_PORT}
      #     - ${REDIS_READ_HOST}:${REDIS_READ_PORT}

  session:
    store-type: redis

  kafka:
    bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}
    consumer:
      group-id: notifications-group

server:
  servlet:
    session:
      timeout: 50s