info:
  app:
    name: dockerProject
    version: '0.1'
    grailsVersion: 6.0.0

grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      enable_cache: false
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
  gorm:
    reactor:
      events: false
  app:
    storagePath: storage/images
  
server:
  port: 8080

hibernate:
  hbm2ddl:
    auto: update
  dialect: org.hibernate.dialect.PostgreSQLDialect
  jdbc:
    batch_size: 25

dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/appDB
  username: admin
  password: 12345678

  