spring:
  
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${CATALOG_DB_URL}:${CATALOG_DB_PORT}/${CATALOG_DB}
    username: ${CATALOG_DB_USERNAME}
    password: ${CATALOG_DB_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}

management:
    tracing:
        sampling:
            probability: 1.0
tracing:
    url: http://${JAEGER_HOST}:${JAEGER_PORT}