spring:
  
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    # url: jdbc:postgresql://${CATALOG_DB_URL}:${CATALOG_DB_PORT}/${CATALOG_DB}
    # username: ${CATALOG_DB_USERNAME}
    # password: ${CATALOG_DB_PASSWORD}
