apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: notifications-db
    type: local
  name: notifications-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/Pavel/temp/notificationsDB"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: notifications-db
  name: notifications-db-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications-db
  name: notifications-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notifications-db
    spec:
      containers:
        - name: notifications-db
          image: postgres:15
          env:
          - name: POSTGRES_DB
            value: 'notificationsDB'
          - name: POSTGRES_USER
            value: 'admin'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notifications-db-passwd
                key: passwd
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: notifications-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: notifications-db-volume
          persistentVolumeClaim:
            claimName: notifications-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications-db
  name: notifications-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: notifications-db