apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-commander
  name: redis-commander
spec:
  selector:
    app: redis-commander
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081